global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'
  receiver: 'gmail'
  # grouping definition
  group_by: ['alertname', 'Service', 'Stage', 'Role']
  group_wait:      30s
  group_interval:  1m
  repeat_interval: 1m


receivers:
- name: 'gmail'
  email_configs:
  - to: 'sreeharshagcp001@gmail.com'
    from: 'sreeharshagcp001@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'sreeharshagcp001@gmail.com'
    auth_identity: 'sreeharshagcp001@gmail.com'
    auth_password: 'fxixpyjubropjngr'

- name: 'slack-notifications'
  slack_configs:
  - channel: '#devsecopsb35'
    send_resolved: true
    title: |-
     [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
     {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
       {{" "}}(
       {{- with .CommonLabels.Remove .GroupLabels.Names }}
         {{- range $index, $label := .SortedPairs -}}
           {{ if $index }}, {{ end }}
           {{- $label.Name }}="{{ $label.Value -}}"
         {{- end }}
       {{- end -}}
       )
     {{- end }}
    text: >-
     {{ range .Alerts -}}
     *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

     *Description:* {{ .Annotations.description }}

     *Details:*
       {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
       {{ end }}
     {{ end }}